import type { Permission } from '../interfaces/permission.interface';
import type { Role } from '../interfaces/role.interface';
import { PERMISSIONS } from './permissions.constants';
import { ROLES } from './roles.constants';

const USER_PERMISSIONS: Permission[] = [
  PERMISSIONS.LISTINGS_CREATE,
  PERMISSIONS.LISTINGS_READ,
  PERMISSIONS.LISTINGS_UPDATE,
  PERMISSIONS.LISTINGS_DELETE,
  PERMISSIONS.LISTINGS_STATS_READ,
  PERMISSIONS.LISTINGS_REPORTS_CREATE,
  PERMISSIONS.LISTINGS_BOOST_CREATE,
  PERMISSIONS.CATEGORIES_READ,
  PERMISSIONS.VARIANTS_READ,
  PERMISSIONS.USERS_ME_READ,
  PERMISSIONS.FAVORITES_CREATE,
  PERMISSIONS.FAVORITES_DELETE,
  PERMISSIONS.COMMENTS_CREATE,
  PERMISSIONS.COMMENTS_DELETE,
  PERMISSIONS.RATINGS_CREATE,
  PERMISSIONS.CONTACT_REQUESTS_CREATE,
  PERMISSIONS.CONTACT_REQUESTS_UPDATE,
  PERMISSIONS.CALENDAR_READ,
  PERMISSIONS.CALENDAR_CREATE,
  PERMISSIONS.CALENDAR_UPDATE,
  PERMISSIONS.CALENDAR_DELETE,
];

const MODERATOR_PERMISSIONS: Permission[] = [
  ...USER_PERMISSIONS,
  PERMISSIONS.LISTINGS_REPORTS_READ,
  PERMISSIONS.LISTINGS_REPORTS_UPDATE,
  PERMISSIONS.COMMENTS_MANAGE_ANY,
  PERMISSIONS.USERS_READ,
  PERMISSIONS.USERS_ACTIVATE,
];

const ADMIN_PERMISSIONS: Permission[] = [
  ...MODERATOR_PERMISSIONS,
  PERMISSIONS.LISTINGS_MANAGE_ANY,
  PERMISSIONS.LISTINGS_STATS_READ_ANY,
  PERMISSIONS.APPOINTMENTS_MANAGE_ANY,
  PERMISSIONS.CONTACT_REQUESTS_MANAGE_ANY,
  PERMISSIONS.CATEGORIES_CREATE,
  PERMISSIONS.CATEGORIES_UPDATE,
  PERMISSIONS.CATEGORIES_DELETE,
  PERMISSIONS.VARIANTS_CREATE,
  PERMISSIONS.VARIANTS_UPDATE,
  PERMISSIONS.VARIANTS_DELETE,
  PERMISSIONS.USERS_ROLE_UPDATE,
  PERMISSIONS.CONTACT_CONFIG_READ,
  PERMISSIONS.CONTACT_CONFIG_UPDATE,
  PERMISSIONS.LEGAL_UPDATE,
  PERMISSIONS.LISTINGS_EXPORT,
];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.OWNER]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: ADMIN_PERMISSIONS,
  [ROLES.MODERATOR]: MODERATOR_PERMISSIONS,
  [ROLES.USER]: USER_PERMISSIONS,
};
