import type { Permission } from '../interfaces/permission.interface';
import type { Role } from '../interfaces/role.interface';
import { PERMISSIONS } from './permissions.constants';
import { ROLES } from './roles.constants';

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.OWNER]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: [
    PERMISSIONS.LISTINGS_CREATE,
    PERMISSIONS.LISTINGS_READ,
    PERMISSIONS.LISTINGS_UPDATE,
    PERMISSIONS.LISTINGS_DELETE,
    PERMISSIONS.CATEGORIES_CREATE,
    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.CATEGORIES_UPDATE,
    PERMISSIONS.CATEGORIES_DELETE,
    PERMISSIONS.VARIANTS_CREATE,
    PERMISSIONS.VARIANTS_READ,
    PERMISSIONS.VARIANTS_UPDATE,
    PERMISSIONS.VARIANTS_DELETE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.CONTACT_CONFIG_READ,
    PERMISSIONS.CONTACT_CONFIG_UPDATE,
    PERMISSIONS.CONTACT_REQUESTS_UPDATE,
    PERMISSIONS.LEGAL_UPDATE,
    PERMISSIONS.CALENDAR_READ,
    PERMISSIONS.CALENDAR_CREATE,
    PERMISSIONS.CALENDAR_UPDATE,
    PERMISSIONS.CALENDAR_DELETE,
  ],
  [ROLES.USER]: [
    PERMISSIONS.LISTINGS_READ,
    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.VARIANTS_READ,
    PERMISSIONS.USERS_ME_READ,
    PERMISSIONS.FAVORITES_CREATE,
    PERMISSIONS.FAVORITES_DELETE,
    PERMISSIONS.COMMENTS_CREATE,
    PERMISSIONS.RATINGS_CREATE,
    PERMISSIONS.CONTACT_REQUESTS_CREATE,
    PERMISSIONS.CALENDAR_READ,
    PERMISSIONS.CALENDAR_CREATE,
    PERMISSIONS.CALENDAR_UPDATE,
    PERMISSIONS.CALENDAR_DELETE,
  ],
};
